module.exports = {
	config: {
		name: "girl",
		aliases: ["girl"],
		version: "1.0",
		author: "AceGun",
		countDown: 5,
		role: 0,
		shortDescription: "send you a girl photos",
		longDescription: "",
		category: "media",
		guide: "{pn}"
	},

	onStart: async function ({ message }) {
	 var link = [
"https://i.postimg.cc/wTJNSC1G/E-B9ea-WQAAst-Yg.jpg",
"https://i.postimg.cc/sgrWyTSD/E-B9eb-AWUAINyt-B.jpg",
"https://i.postimg.cc/TYcj48LJ/E02i-P-q-XIAE62tu.jpg",
"https://i.postimg.cc/MpK0ks12/E02i-P-w-WYAEbvgg.jpg",
"https://i.postimg.cc/k5LWbqzq/E02i-P-x-XIAAy-K2k.jpg",
"https://i.postimg.cc/C5R1Hqq2/E067-KUr-VIAYK-4-R.jpg",
"https://i.postimg.cc/v8KD80Rw/E067-KUs-Uc-AM2jri.jpg",
"https://i.postimg.cc/xCJD6y6L/E07-FXgt-UYAAp-Qn-S.jpg",
"https://i.postimg.cc/q77d3dnb/E07-FXgu-Uc-AQB1-RK.jpg",
"https://i.postimg.cc/pXPcTJKk/E08z-UBs-Xo-AMh-F2-F.jpg",
"https://i.postimg.cc/wBR0Pfdx/E08z-UBu-WUAMx-KL8.jpg",
"https://i.postimg.cc/3RWbK8ph/E0cw-VJp-Vo-AMw8g-C.jpg",
"https://i.postimg.cc/250KRb1T/E0cw-VJr-UYAAvdpk.jpg",
"https://i.postimg.cc/7LHWWMZf/E0iwcu-XUYAIk-OOs.jpg",
"https://i.postimg.cc/rwLbSL6G/E0iwcu-XVUAAEUC.jpg",
"https://i.postimg.cc/qRYDqPX3/E0-JLpim-XMAMNpcx.jpg",
"https://i.postimg.cc/kgFHsh90/E0-JLpio-XIAAg-Xm9.jpg",
"https://i.postimg.cc/44qjx9BS/E0-JOIXn-WYAQht-Ed.jpg",
"https://i.postimg.cc/MKBNMpLK/E0-JOIXq-Xo-AMY0w-F.jpg",
"https://i.postimg.cc/mZz6JrBN/E0rf0jh-XIAYVIHN.jpg",
"https://i.postimg.cc/ryBYkLp6/E0rf0jj-Xo-AMG-x-X.jpg",
"https://i.postimg.cc/y8PfcgyB/E0s-Ky-B-WYAESuzb.jpg",
"https://i.postimg.cc/J4jY7dys/E0s-Ky-B9-Xo-AAZBEM.jpg",
"https://i.postimg.cc/ZnsNJmrG/E11dmj-HVg-AIg-At-V.jpg",
"https://i.postimg.cc/DfxLrrtx/E11dmjl-UUAQs-Qhm.jpg",
"https://i.postimg.cc/Zq5wcbwN/E1-BXp7-MVo-Ag-Cp-I.jpg",
"https://i.postimg.cc/4NRw0b8s/E1-BXp7-OVg-AAZVMI.jpg",
"https://i.postimg.cc/mDcVvdf2/E1-Go-Jmx-UUAQ6-Cmu.jpg",
"https://i.postimg.cc/DfXB5YPx/E1-Go-Jmx-VEAEt-Pw-V.jpg",
"https://i.postimg.cc/65Vzx2SR/E1lf-Kh4-VEAMRmp-S.jpg",
"https://i.postimg.cc/D0L6Z8w9/E1lf-Kh6-VIAYBZdy.jpg",
"https://i.postimg.cc/HkB2VGTk/E1qu0k-LVEAcs-Dld.jpg",
"https://i.postimg.cc/zfvkhdfS/E1qu0k-MUc-AEJPwv.jpg",
"https://i.postimg.cc/zBRStVKy/E1-RCTm9-Xo-AEqbv8.jpg",
"https://i.postimg.cc/cCy7V0BX/E1-RCTn-AWQAIt-Bp-E.jpg",
"https://i.postimg.cc/QCQgDw6s/E1v-KZ7q-WQAAZP7h.jpg",
"https://i.postimg.cc/c1wBftdj/E1v-KZ7r-XMAUxu-Tm.jpg",
"https://i.postimg.cc/dtDd47Fw/E29-Siqm-WEAYUVQ1.jpg",
"https://i.postimg.cc/mgH9W0hn/E29-Siqm-Xo-Ak-P0ne.jpg",
"https://i.postimg.cc/rwn1qS9d/E2-Ex23-KXEAEsg-Y.jpg",
"https://i.postimg.cc/2514yVH0/E2-Ex23-TXIAE-sne.jpg",
"https://i.postimg.cc/NFcTdbQn/E2g-0ed-Xo-AET0yb.jpg",
"https://i.postimg.cc/KjDTwLz8/E2g-0ef-WYAAh3le.jpg",
"https://i.postimg.cc/zDCTymjY/E2-Wub-N1-WEAAZ6f-M.jpg",
"https://i.postimg.cc/L6mLfyCY/E2-Wub-N3-WQAMAq-E2.jpg",
"https://i.postimg.cc/CKnqY91t/E2zceu8-XIAUxxg-Z.jpg",
"https://i.postimg.cc/kgpb07nK/E2zcev-GXw-AE7a0d.jpg",
"https://i.postimg.cc/pTqhBv1m/E31j-E9f-XMAEh-GLW.jpg",
"https://i.postimg.cc/N0vHspHj/E31j-E9g-XIAQZ-VM.jpg",
"https://i.postimg.cc/hG87fTLb/E32-Bx-EOVk-Ao-z64.jpg",
"https://i.postimg.cc/76xJ7hXv/E32-Bx-EPVUAE9-W89.jpg",
"https://i.postimg.cc/gj7xfDpd/E36pnk-Vc-AMvnb2.jpg",
"https://i.postimg.cc/5yyH7rZn/E36pnk7-Vo-AQwv7-S.jpg",
"https://i.postimg.cc/FFCkd9Lq/E36pnk9-UUAY7-DB0.jpg",
"https://i.postimg.cc/KvQL5nw9/E3aa-EGf-VIAIOWVx.jpg",
"https://i.postimg.cc/x1CmpXS9/E3aa-EGf-Vk-AEu-8-U.jpg",
"https://i.postimg.cc/V6ybN40N/E3-Ev8zh-Xw-AAi-Icl.jpg",
"https://i.postimg.cc/d18ZZdGj/E3-Ev8zo-XMAMf-4t.jpg",
"https://i.postimg.cc/1XsnGtHh/E3g-Gz-Qt-Uc-AMs-Bf4.jpg",
"https://i.postimg.cc/j2cWZbgW/E3g-Gz-Qt-VIAQYj-Nv.jpg",
"https://i.postimg.cc/3xVkL9BZ/E3p-Wu-Xb-XIAI-Jn-R.jpg",
"https://i.postimg.cc/8PyJvTf9/E3p-Wu-XZXMAEc-Kc-F.jpg",
"https://i.postimg.cc/TPbpBmNv/E3-SHCr-XWYAEXRLv.jpg",
"https://i.postimg.cc/qRdzrRWh/E3-SHCr-YX0-AAvxyv.jpg",
"https://i.postimg.cc/brmJ1Rrk/E3ww8qc-Vk-AUMPk-G.jpg",
"https://i.postimg.cc/J7xGwRx0/E3ww8qd-VUAgem-H.jpg",
"https://i.postimg.cc/Fzrzf6rh/E3ww8qe-Vc-AYZcjx.jpg",
"https://i.postimg.cc/s2JvVyzT/E43-RKf-UVg-AMr0-Ax.jpg",
"https://i.postimg.cc/s2zMdxkB/E43-RKf-WVc-AIRt-Hv.jpg",
"https://i.postimg.cc/gkfwsN4H/E48bjsr-WUAE5w00.jpg",
"https://i.postimg.cc/x1MX4M4D/E48bjss-X0-AAou-Wg.jpg",
"https://i.postimg.cc/Dw8WdRqZ/E4-C3-sd-Xw-AA9ujr.jpg",
"https://i.postimg.cc/gJqr2pPM/E4-C3-sj-WEAIy-PXt.jpg",
"https://i.postimg.cc/J4htMSYq/E4d5-Mh9-XEAM-py5.jpg",
"https://i.postimg.cc/XYGJydbB/E4d5-Mi-AXw-AAv-QJr.jpg",
"https://i.postimg.cc/CKbxc0dF/E4-KKLu9-UYAg-BCN4.jpg",
"https://i.postimg.cc/rmcFbHt5/E4-KKLu-Uc-AAw9-Oj.jpg",
"https://i.postimg.cc/tT5CHzhw/E4p-UTo7-Vg-AMt-JS6.jpg",
"https://i.postimg.cc/Gtm33sK2/E4p-UTo7-Vo-AAZZEc.jpg",
"https://i.postimg.cc/fTkW6mkq/E4sn-P1a-UUAcf6-Nd.jpg",
"https://i.postimg.cc/v80Hq386/E4sn-P1a-VEAQAJv9.jpg",
"https://i.postimg.cc/sxHjMDHJ/E4-Tu-ORr-XIAYDJk.jpg",
"https://i.postimg.cc/yY56BxZ1/E4-Tu-ORs-WUAAXMIV.jpg",
"https://i.postimg.cc/HL1pcNzF/E4um-Bm-EVk-AUWf